source 'https://rubygems.org'
ruby '2.1.1'
gem 'rails'
gem 'actionmailer'
gem 'rake'
gem 'sass'
gem 'haml'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-ui-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'foundation-rails'
gem 'foundation-icons-sass-rails'
gem 'mandrill-rails'
gem 'pg'
gem 'sprockets', '2.11.0'
gem 'will_paginate'
gem 'yaml_db'
gem 'stripe'
gem 'json'
gem 'copycopter_client', '2.0.0'
gem 'hpricot'
gem 'prawn'
gem 'country_select'
gem 'dynamic_form'
gem 'unicorn'
gem 'newrelic_rpm'
gem 'carrierwave_direct'
gem 'fog'
gem 'delayed_job_active_record'
gem 'barby'
gem 'groupdate'
gem 'chartkick'
gem 'sendgrid'
gem 'nearest_time_zone'
gem 'unf'
gem 'ruby-hl7'


group :production do
  gem 'rails_12factor'
end

group :development do
  gem 'rspec-rails'
  gem 'annotate'
  gem 'faker'
  gem 'awesome_print'
  gem 'meta_request'
  gem 'haml-rails'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem "bullet"
end