development:
  encoding: unicode
  adapter: postgresql
  host: localhost
  database: pursay_demo_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: pursay_demo_test
  pool: 5